# -*- coding: utf-8 -*-
"""Order List-Bryan Hernandez-Henry Muñoz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6-vtyecnuVo9XH6qt08xcXumsuE6WUC
"""

class OrderList:

    # initial_elements: permite iniciar la colección con algunos elementos
    def __init__(self, initial_elements=[]):
        self.data = sorted(list(initial_elements))

    # devuelve una cadena de texto con los elementos de la colección
    def __str__(self):
        return str(self.data)

    # devuelve la cantidad de elementos que tiene la colección
    def __len__(self):
        return len(self.data)

    # devuelve el elemento de la colección en la posición del índice
    # Error: si el índice no existe
    def __getitem__(self, index):
        if index < 0 or index >= len(self.data):
            raise IndexError("El índice no existe")
        return self.data[index]

    # devuelve un valor booleano que indica si la colección está vacía o no
    def isEmpty(self):
        return len(self.data) == 0

    # permite recorrer la colección con un ciclo for
    def __iter__(self):
        return iter(self.data)

    # devuelve True o False dependiendo si el elemento existe en la colección
    def __contains__(self, element):
        return element in self.data

    # agrega un elemento manteniendo el orden de la lista
    def add(self, element):
        self.data.append(element)
        self.data.sort()

    # elimina un elemento de la colección por su valor
    # Error: si el elemento no existe en la colección
    def remove(self, element):
        if element not in self.data:
            raise ValueError("El elemento no existe en la colección")
        self.data.remove(element)

    # elimina y devuelve el elemento de la colección según su índice
    def pop(self, index):
        if index < 0 or index >= len(self.data):
            raise IndexError("El índice no existe")
        return self.data.pop(index)

    # elimina todos los elementos de la colección
    def clear(self):
        self.data.clear()